(define (problem ex1_strip_plus_p9)
    (:domain ex1_strip_plus)
    ; OBJECT DEFINITION
    (:objects
       depot - location ;; our initial depot
       location1 location2 location3 location4  - location ;; other location avaiable
       robot1 - robot ;; our agent
       box1 box2 box3 box4 - box ;; three box avaiable
       person1 person2 person3 person4 - person ;; person to be rescued
       ; content to be delivered
       content1 content4 content7 content10 - food
       content2 content5 content8 content11 - tool
       content3 content6 content9 content12 - medicine
    )
    ; PREDICATE DEFINITION    
    (:init
        ; all box, content, agent at depot initially
        ; box initial position
        (be_at_box box1 depot)
        (be_at_box box2 depot)
        (be_at_box box3 depot)
        (be_at_box box4 depot)
        ; content initial position
        (be_at_content content1 depot)
        (be_at_content content2 depot)
        (be_at_content content3 depot)
        (be_at_content content4 depot)
        (be_at_content content5 depot)
        (be_at_content content6 depot)
        (be_at_content content7 depot)
        (be_at_content content8 depot)
        (be_at_content content9 depot)
        (be_at_content content10 depot)
        (be_at_content content11 depot)
        (be_at_content content12 depot)
        ; robot initial position
        (be_at_robot depot robot1)
        ; people initial position
        (be_at_person location1 person1)
        (be_at_person location2 person2)
        (be_at_person location3 person3)
        (be_at_person location4 person4)
        ; note that robot and box must be empty
        (empty_robot robot1)
        ; box initial empty
        (empty_box box1)
        (empty_box box2)
        (empty_box box3)
        (empty_box box4)
        (not_is_assigned_box box1)
        (not_is_assigned_box box2)
        (not_is_assigned_box box3)
        (not_is_assigned_box box4)
        ; no content is assigned to anyone
        (not_assigned_person_content content1 person1)
        (not_assigned_person_content content2 person1)
        (not_assigned_person_content content3 person1)
        (not_assigned_person_content content4 person1)
        (not_assigned_person_content content5 person1)
        (not_assigned_person_content content6 person1)
        (not_assigned_person_content content7 person1)
        (not_assigned_person_content content8 person1)
        (not_assigned_person_content content9 person1)
        (not_assigned_person_content content10 person1)
        (not_assigned_person_content content11 person1)
        (not_assigned_person_content content12 person1)
        (not_assigned_person_content content1 person2)
        (not_assigned_person_content content2 person2)
        (not_assigned_person_content content3 person2)
        (not_assigned_person_content content4 person2)
        (not_assigned_person_content content5 person2)
        (not_assigned_person_content content6 person2)
        (not_assigned_person_content content7 person2)
        (not_assigned_person_content content8 person2)
        (not_assigned_person_content content9 person2)
        (not_assigned_person_content content10 person2)
        (not_assigned_person_content content11 person2)
        (not_assigned_person_content content12 person2)
        (not_assigned_person_content content1 person3)
        (not_assigned_person_content content2 person3)
        (not_assigned_person_content content3 person3)
        (not_assigned_person_content content4 person3)
        (not_assigned_person_content content5 person3)
        (not_assigned_person_content content6 person3)
        (not_assigned_person_content content7 person3)
        (not_assigned_person_content content8 person3)
        (not_assigned_person_content content9 person3)
        (not_assigned_person_content content10 person3)
        (not_assigned_person_content content11 person3)
        (not_assigned_person_content content12 person3)
        (not_assigned_person_content content1 person4)
        (not_assigned_person_content content2 person4)
        (not_assigned_person_content content3 person4)
        (not_assigned_person_content content4 person4)
        (not_assigned_person_content content5 person4)
        (not_assigned_person_content content6 person4)
        (not_assigned_person_content content7 person4)
        (not_assigned_person_content content8 person4)
        (not_assigned_person_content content9 person4)
        (not_assigned_person_content content10 person4)
        (not_assigned_person_content content11 person4)
        (not_assigned_person_content content12 person4)        
        ; no box is full
        (not_assigned_box_content box1 content1)
        (not_assigned_box_content box1 content2)
        (not_assigned_box_content box1 content3)
        (not_assigned_box_content box1 content4)
        (not_assigned_box_content box1 content5)
        (not_assigned_box_content box1 content6)
        (not_assigned_box_content box1 content7)
        (not_assigned_box_content box1 content8)
        (not_assigned_box_content box1 content9)
        (not_assigned_box_content box1 content10)
        (not_assigned_box_content box1 content11)
        (not_assigned_box_content box1 content12)
        (not_assigned_box_content box2 content1)
        (not_assigned_box_content box2 content2)
        (not_assigned_box_content box2 content3)
        (not_assigned_box_content box2 content4)
        (not_assigned_box_content box2 content5)
        (not_assigned_box_content box2 content6)
        (not_assigned_box_content box2 content7)
        (not_assigned_box_content box2 content8)
        (not_assigned_box_content box2 content9)
        (not_assigned_box_content box2 content10)
        (not_assigned_box_content box2 content11)
        (not_assigned_box_content box2 content12)
        (not_assigned_box_content box3 content1)
        (not_assigned_box_content box3 content2)
        (not_assigned_box_content box3 content3)
        (not_assigned_box_content box3 content4)
        (not_assigned_box_content box3 content5)
        (not_assigned_box_content box3 content6)
        (not_assigned_box_content box3 content7)
        (not_assigned_box_content box3 content8)
        (not_assigned_box_content box3 content9)
        (not_assigned_box_content box3 content10)
        (not_assigned_box_content box3 content11)
        (not_assigned_box_content box3 content12)
        (not_assigned_box_content box4 content1)
        (not_assigned_box_content box4 content2)
        (not_assigned_box_content box4 content3)
        (not_assigned_box_content box4 content4)
        (not_assigned_box_content box4 content5)
        (not_assigned_box_content box4 content6)
        (not_assigned_box_content box4 content7)
        (not_assigned_box_content box4 content8)
        (not_assigned_box_content box4 content9)
        (not_assigned_box_content box4 content10)
        (not_assigned_box_content box4 content11)
        (not_assigned_box_content box4 content12)
        ; no box is assigned to any robot 
        (not_assigned_robot_box box1 robot1)
        (not_assigned_robot_box box2 robot1)
        (not_assigned_robot_box box3 robot1)
        (not_assigned_robot_box box4 robot1)
        ; no content is assigned
        (not_is_assigned content1)
        (not_is_assigned content2)
        (not_is_assigned content3)
        (not_is_assigned content4)
        (not_is_assigned content5)
        (not_is_assigned content6)
        (not_is_assigned content7)
        (not_is_assigned content8)
        (not_is_assigned content9)
        (not_is_assigned content10)
        (not_is_assigned content11)
        (not_is_assigned content12)
    )
    ; GOAL DEFINITION
    (:goal
        (and
		; deliver food
		(or
		    (assigned_person_content content1 person1)
		    (assigned_person_content content4 person1)
		    (assigned_person_content content7 person1)
		    (assigned_person_content content10 person1)
		)
		(or
		    (assigned_person_content content1 person2)
		    (assigned_person_content content4 person2)
		    (assigned_person_content content7 person2)
		    (assigned_person_content content10 person2)
		)
		; deliver tool
		(or
		    (assigned_person_content content2 person1)
		    (assigned_person_content content5 person1)
		    (assigned_person_content content8 person1)
		    (assigned_person_content content11 person1)
		)
		(or
		    (assigned_person_content content2 person3)
		    (assigned_person_content content5 person3)
		    (assigned_person_content content8 person3)
		    (assigned_person_content content11 person3)
		)
		; deliver medicine
		(or
		    (assigned_person_content content3 person1)
		    (assigned_person_content content6 person1)
		    (assigned_person_content content9 person1)
		    (assigned_person_content content12 person1)
		)
		(or
		    (assigned_person_content content3 person4)
		    (assigned_person_content content6 person4)
		    (assigned_person_content content9 person4)
		    (assigned_person_content content12 person4)
		)
	)
           
    )
)
